In [3]:
import seaborn as sns
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from IPython.html.widgets import interact
from dautil import data
from dautil import ts

ImportError: No module named 'pandas_datareader'

In [10]:
a = np.array([[11, 12, 13], [14, 15, 16], [17, 18, 19]])

In [11]:
print (a)

[[11 12 13]
 [14 15 16]
 [17 18 19]]


In [12]:
a[0]

array([11, 12, 13])

In [13]:
a[1]

array([14, 15, 16])

In [14]:
a[1,2]

16

In [15]:
c = a[:2]

In [16]:
c

array([[11, 12, 13],
       [14, 15, 16]])

In [17]:
a[:]

array([[11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

In [19]:
a = np.array(range(10))

In [20]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
b = (a**2)
b

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [24]:
a = np.array([1,0,1,0])
b = np.array([1,0,0,0])

In [25]:
np.logical_and(a,b)

array([ True, False, False, False])

In [27]:
a = np.array([[0, 5, 10], [20, 25, 30]])
a

array([[ 0,  5, 10],
       [20, 25, 30]])

In [29]:
a = np.array([[12,4], [3,15]])
a

array([[12,  4],
       [ 3, 15]])

In [30]:
np.sum(a)

34

In [34]:
np.sum(a, axis=0) # suma por columnas

array([15, 19])

In [36]:
np.sum(a, axis=1) # suma por filas

array([16, 18])

In [37]:
import pandas as pd

In [48]:
data = {'Year': [2000, 2005, 2010, 2014],
'Median_Age': [24.2, 26.4, 28.5, 30.3],
        'Density': [244, 256, 268, 279]}

df = pd.DataFrame(data, columns=['Year', 'Density',
'Median_Age'], index=['a', 'b', 'c', 'd'])
df

Year  Density  Median_Age
a  2000      244        24.2
b  2005      256        26.4
c  2010      268        28.5
d  2014      279        30.3

In [49]:
df.index

Index([u'a', u'b', u'c', u'd'], dtype='object')

In [52]:
df.ix['b']

Year          2005.0
Density        256.0
Median_Age      26.4
Name: b, dtype: float64

In [45]:
data = {'Year': [2000, 2005, 2010, 2014],
'Median_Age': [24.2, 26.4, 28.5, 30.3],
        'Density': [244, 256, 268, 279]}

df = pd.DataFrame(data, columns=['Year', 'Density',
'Median_Age'])
df

Year  Density  Median_Age
0  2000      244        24.2
1  2005      256        26.4
2  2010      268        28.5
3  2014      279        30.3

In [46]:
df.index

RangeIndex(start=0, stop=4, step=1)

In [47]:
df.ix[1]

/home/reroes/entornos/envdataanalisis/lib/python2.7/site-packages/ipykernel_launcher.py:1: DeprecationWarning: 
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated
  """Entry point for launching an IPython kernel.


Year          2005.0
Density        256.0
Median_Age      26.4
Name: 1, dtype: float64